### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by ItsShiv1** [BYU-PRISM/Seeq#43]
Facing a issue while installing the addon - When I am executing this command on seeq terminal  "python -m seeq_sysid"
Error is :
Traceback (most recent call last):
  File "/home/datalab/.local/lib/python3.8/site-packages/seeq_sysid/__main__.py", line 100, in logging_attempts
    spy.login(username=_user, password=passwd, ignore_ssl_errors=True)
  File "/home/datalab/.local/lib/python3.8/site-packages/seeq/spy/_login.py", line 171, in login
    _login(username, password, access_key, url, directory, ignore_ssl_errors, proxy,
  File "/home/datalab/.local/lib/python3.8/site-packages/seeq/spy/_login.py", line 230, in _login
    validate_seeq_server_version(
  File "/home/datalab/.local/lib/python3.8/site-packages/seeq/spy/_login.py", line 772, in validate_seeq_server_version
    sdk_module_major, sdk_module_minor, _ = get_sdk_module_version_tuple()
  File "/home/datalab/.local/lib/python3.8/site-packages/seeq/spy/_login.py", line 619, in get_sdk_module_version_tuple
    seeq_module_major = int(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/datalab/.local/lib/python3.8/site-packages/seeq_sysid/__main__.py", line 149, in <module>
    logging_attempts(user)
  File "/home/datalab/.local/lib/python3.8/site-packages/seeq_sysid/__main__.py", line 102, in logging_attempts
    except (SPyRuntimeError, SPyValueError):

**Comment by anvenkat18** [comment]
Hello @ItsShiv1 
I was able to reproduce your issue on R56. It looks like you are running an older version of SPy. Can you upgrade SPy to 184 and try installing? That fixed it for me.

  `pip install seeq~=56.1.9.184.21` from the data lab terminal to upgrade seeq

**Comment by ItsShiv1** [comment]
Hello @anvenkat18 
I upgraded the SPy to 184, still I am getting the same error 
![image](https://user-images.githubusercontent.com/128075557/226279044-518e24e1-0682-4759-ac0d-8aa1c9f093ab.png)
Could you please check it let me the fix possible.

**Comment by anvenkat18** [comment]
Thanks for the update @ItsShiv1 and good to hear its working at your end. What version did you upgrade Seeq and data lab to?

**Comment by anvenkat18** [comment]
@ItsShiv1 
We can reproduce what you are seeing on R56. It works fine on R58+. Looks like a regression of some sort. We are looking into it. Are you on R56?

**Comment by ItsShiv1** [comment]
@anvenkat18 lets connect on a teams call, Can you give us your mail ID so I will send you the invite and we can connect .
Yes I am on R56.1.5

**Comment by ItsShiv1** [comment]
@imanbabaei, @anvenkat18 Can we connect on teams call to discuss this issue between 2pm -11pm IST,25 March

**Comment by imanbabaei** [comment]
Hi @ItsShiv1,
Thank you very much for your time and patience. I am available for the meeting.
We just released seeq-sysid==v0.7.1 and removed a couple of dependencies to avoid conflicts with pre-installed packages on DataLab. 
Could you please try it and let us know if that solves the issue?

**Comment by ItsShiv1** [comment]
@anvenkat18, @imanbabaei Thank you for kind support and Yes its working now hence we can close this issue.
